### ISSUE TITLE
Error: Invalid version. Must be a string. Got type "object".

### ISSUE THREAD

**Issue by lucabiffi** [gavanlamb/.net-outdated#42]
Hi I'm trying to use this action on github but I get the error

> Error: Invalid version. Must be a string. Got type "object".

I didn't know which package is the problem, so I created a mock project to test different solutions. I still didn't find which package causes the error but I found something interesting. I installed NLog and fiddling with different versions I was able to reproduce the error, here are my tests:
Installed 5.3.4 (latest version) -> .net-outdated works
Downgrade 1.0.0.505 -> .net-outdated breaks
Upgrade 2.0.0.2000 -> .net-outdated breaks
Upgrade 2.0.1.2 -> .net-outdated breaks
Installed 4.0.0 -> .net-outdated works

You can look at my PR with different tries here: [Example PR](https://github.com/lucabiffi/MyNetProject/pull/1)

I'm not sure what's happening but my feeling is that in summaryService.ts, in function getDetailedBody this line could cause the problem:
`versionDifference: semverDiff.default(topLevelPackage.requestedVersion!, topLevelPackage.latestVersion)`

PS:
another minor thing, in your readme there's a copy-paste error because you mention _.net-vulnerable@latest_ but probably you meant _.net-outdated@latest_

**Comment by gavanlamb** [comment]
Hi @lucabiffi, 

Thanks for taking the time to look into this and for raising an issue.

The package versions are an assembly version when a semver is expected. 

In 2017 NuGet moved to semver versioning. The idea with this action was to support current standards. 

The changes should support the assembly version. 

Please upgrade to version 1.0.1.

**Comment by lucabiffi** [comment]
Hi @gavanlamb,
thank you for such a prompt response and fix!
I confirm this is working now in my repositories

Cheers
